---
# tasks file for user_management


- name: Create users
  become: true
  ansible.builtin.user:
    name: "{{ item.username }}"
    state: "{{ item.state | default(omit)  }}"
    uid: "{{ item.uid | default(omit)  }}"
    ssh_key_file: "{{ item.ssh_keyfile | default(omit)  }}"
    password: "{{ item.password | default(omit)  }}"
    system: "{{ item.system | default(omit)  }}"
    home: "{{ item.home | default(omit)  }}"
    group: "{{ item.group | default(omit)  }}"
    groups: "{{ item.groups | default(omit)  }}"
    create_home: "{{ item.create_home | default(omit)  }}"
    comment: "{{ item.comment | default(omit) }}"

